---
title: "experiments"
format: html
---

```{r}
library(tidyverse)
library(logolink)
```

```{r}
model_path <- file.path("netlogo", "roads", "Segregation Utility.nlogox")
model_path <- "C:/Users/vsesu60/OneDrive - Linköpings universitet/Documents/R/vis-soc/netlogo/roads/Segregation Utility.nlogox"
```

```{r}
setup_file <- create_experiment(
  name = "Venue Segragation Model Analysis",
  repetitions = 2,
  run_metrics_every_step = TRUE,
  setup = "setup",
  go = "go",
  time_limit = 200,
  metrics = c(
  'index-exposure',
  'index-dissimilarity',
  'index-clustering',
  'index-centrality',
  'index-concentration'
  ),
  constants = list(
    "density-percent" = c(70),
    "%-similar-wanted" = 30,
    "number-of-ethnicities" = 2,
    "%-different-wanted" = 0,
    "neighborhood-distance" = c(2),
    "venues-number" = c(5),
    "venue-catchment-distance" = c(1, 3, 10, 15),
    "venue-exclusivity" = 1,
    "utility-threshold" = 0.1,
    "beta1-neighbors" = c(0.5),
    "beta2-venue-group" = 0.5,
    "beta3-venue-loc" = 0,
    "beta4-home-venues" = 0,
    "road-scenario" = 'empty',
    "parks-number" = 3,
    "park-catchment-distance" = 2,
    "beta5-park-group" = 0.25,
    "travel-distance" = 5,
    "road-multiplier" = 1,
    "real-travel?" = F,
    "random-seed?" = F
  )
)


```

```{r}
setup_file |> inspect_experiment()
```


```{r}
results <-
  model_path |>
  run_experiment(
    setup_file = setup_file,
    output = c("table", "lists")
  )
```

```{r}
results |> glimpse()
```

```{r}
library(magrittr)
data <-
  results |>
  extract2("table") 
```


### Segregation Indices Over Time by Neighborhood Distance

```{r}
data |> 
  filter(step <= 200) |> 
  select(
    run_number,
    step,
    starts_with("index_"),
    venue_catchment_distance         
  ) |> 
  pivot_longer(
    cols = starts_with("index_"),
    names_to = "index",
    values_to = "value"
  ) |> 
  filter(index %in% c("index_exposure", "index_dissimilarity", 
                      "index_clustering")) |>
  mutate(grouping_combo_run = str_c(run_number, index, venue_catchment_distance),
         grouping_combo_condition = str_c(index, venue_catchment_distance)) |> 
  ggplot(aes(x = step, y = value, color = index, group = grouping_combo_run)) +
  geom_line(alpha = 0.25)+
  facet_wrap(~ venue_catchment_distance)+
  geomtextpath::geom_textpath(
    aes(group = grouping_combo_condition, color = index, label = index), 
    offset = unit(5, "pt"), gap = T, text_smoothing = 100)+
  labs(title = "Segregation Indices Over Time (venue_catchment_distance)", x = "Step", 
       y = "Index Value", color = "Index") +
  theme_minimal()+
  theme(legend.position = "none")
       
```


### function

```{r}

input_to_vis <- function(model_path, constrain, values = c()){
  # function takes the model path
  # the name of the constraint to be varied and a vector of values for that constraint
  # it creates an experiment file and runs the experiment, returning the results as a graph
  
}
```



```{r}
model_path <-
  find_netlogo_home() |>
  file.path(
    "models",
    "IABM Textbook",
    "chapter 4",
    "Wolf Sheep Simple 5.nlogox"
  )

setup_file <- create_experiment(
  name = "Wolf Sheep Simple Model Analysis",
  setup = "setup",
  go = "go",
  time_limit = 500,
  run_metrics_condition = 'ticks mod 100 = 0',
  metrics = c(
    '[xcor] of sheep',
    '[ycor] of sheep',
    '[xcor] of wolves',
    '[ycor] of wolves',
    '[pxcor] of patches',
    '[pycor] of patches',
    '[pcolor] of patches'
  ),
  constants = list(
    "number-of-sheep" = 100,
    "number-of-wolves" = 15,
    "movement-cost" = 0.5,
    "grass-regrowth-rate" = 0.3,
    "energy-gain-from-grass" = 2,
    "energy-gain-from-sheep" = 5
  )
)
```

```{r}
create_experiment_template(model_path, insert_at_cursor = TRUE)

setup_file <- create_experiment(
  name = "Auto-Generated Analysis",
  repetitions = 1,
  run_metrics_every_step = TRUE,
  setup = "setup",
  go = "go",
  time_limit = 200,
  metrics = c(
    "percent-similar",
    "percent-unhappy",
    "index-exposure",
    "index-dissimilarity",
    "index-clustering",
    "index-centrality",
    "index-concentration",
    "[pxcor] of patches",
    "[pycor] of patches",
    "[pcolor] of patches"
  ),
  constants = list(
    "density-percent" = c(71.0),
    "%-similar-wanted" = c(30.0),
    "number-of-ethnicities" = c(2.0),
    "%-different-wanted" = c(0.0),
    "neighborhood-distance" = c(1.0),
    "venues-number" = c(4.0),
    "venue-catchment-distance" = c(11.0),
    "venue-exclusivity" = c(1.0),
    "utility-threshold" = c(0.1),
    "beta1-neighbors" = c(0.1),
    "beta2-venue-group" = c(0.1),
    "beta3-venue-loc" = c(0.1),
    "beta4-home-venues" = c(0.1),
    "parks-number" = c(1.0),
    "park-catchment-distance" = c(10.0),
    "beta5-park-group" = c(0.1),
    "travel-distance" = c(9.0),
    "road-multiplier" = c(1.0),
    "real-travel?" = c(FALSE),
    "random-seed?" = c(FALSE),
    "new-venue-color" = c(15.0),
    "visual-mode" = c("abstract"),
    "road-scenario" = c("empty")
  )
)
```

